### ISSUE TITLE
Is it suitable with sidekiq-unique-jobs?

### ISSUE THREAD

**Issue by tamvm** [krainboltgreene/paper_trail-background.rb#3]
In Installation instruction, in `VersionJob` you suggested:

```
  # These are settings you'll probably want, I suggest sidekiq-unique-jobs
  sidekiq_options(
    :queue => "versions",
    :unique_across_queues => true,
    :lock => :until_executed,
    :log_duplicate_payload => true
  )
```

While in the sidekiq-unique-jobs gem, they clearly state that they haven't support for ActiveJob https://github.com/mhenrixon/sidekiq-unique-jobs/wiki/About-ActiveJob, is it this gem: https://github.com/mhenrixon/sidekiq-unique-jobs/ you are mentioning in the installation guide? 

Moreover, `sidekiq_options` is also only available in `Sidekiq::Worker`, so when I used your code, it raised this exception: 

```
NoMethodError:
  undefined method `sidekiq_options' for VersionJob:Class
  Did you mean?  sidekiq_delay_until
```

Many thanks,

**Comment by krainboltgreene** [comment]
Yes, I don't use ActiveJob precisely for the reasons you've listed. See: https://github.com/mperham/sidekiq/wiki/Active-Job
