### ISSUE TITLE
didn't detect the roll back

### ISSUE THREAD

**Issue by Hammam94** [krainboltgreene/paper_trail-background.rb#7]
there is an issue that if there is an exception occurs during the after_save callback this will cause a rollback and the record will get removed but the version job is created and gets stuck as it tries to find a non-existing record, how should i solve this issue

**Comment by Hammam94** [comment]
i figured the problem is here the following line in `background.rb` class 
`ActiveRecord::Base.after_transaction` as this makes the block run immediately 
and i changed it to 
`record.class.after_transaction` and this works fine form the ar_after_transaction gem now watched the rollback the occurs in after_save callback

did you wanna me make a PR

**Comment by krainboltgreene** [comment]
Fixed, thanks for pointing that out.
